#!/bin/bash

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

yabai -m config layout bsp

# New window spawns to the right if vertical split, or bottom if horizontal split
yabai -m config window_placement second_child

# Set all padding and gaps to 20pt (default: 0)
yabai -m config top_padding    20
yabai -m config bottom_padding 20
yabai -m config left_padding   20
yabai -m config right_padding  20
yabai -m config window_gap     20


# set mouse interaction modifier key (default: fn)
yabai -m config mouse_modifier alt

# set modifier + left-click drag to move window (default: move)
yabai -m config mouse_action1 move

# set modifier + right-click drag to resize window (default: resize)
yabai -m config mouse_action2 resize

# set focus follows mouse mode (default: off, options: off, autoraise, autofocus)
yabai -m config focus_follows_mouse autofocus

# set mouse follows focus mode (default: off)
yabai -m config mouse_follows_focus on

# modify window shadows (default: on, options: on, off, float)
# example: show shadows only for floating windows
yabai -m config window_shadow float

# window opacity (default: off)
# example: render all unfocused windows with 90% opacity
yabai -m config window_opacity on
yabai -m config active_window_opacity 0.97
yabai -m config normal_window_opacity 0.90

# Animation Settings
# yabai -m config window_animation_duration 0.1
# yabai -m config window_animation_easing easeIn


# add 20 padding to the top and 0 padding to the bottom of every space located on the main display
yabai -m config external_bar all:20:0

# Dont manage
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^app_gma3$" manage=on
yabai -m rule --add app="^grandMA3$" manage=off
yabai -m rule --add app="^Raycast$" manage=off
yabai -m rule --add app="^Logic Pro$" manage=on
yabai -m rule --add app="^VBAN Receptor$" manage=off
yabai -m rule --add app="^Unreal Editor$" manage=off
yabai -m rule --add app="^Python$" manage=off


# Not Tranparent
yabai -m rule --add app="^Noodl Editor$" opacity=1.0
yabai -m rule --add app="^Adobe Lightroom$" opacity=1.0
yabai -m rule --add app="^Arc$" opacity=1.0


yabai -m rule --add app="^Adobe Photoshop 2024$" opacity=1.0
yabai -m rule --add app="^Lightroom Classic$" opacity=1.0
yabai -m rule --add app="^DaVinci Resolve$" opacity=1.0

yabai -m rule --add app="^Code$" opacity=0.95

# Float by Default
yabai -m rule --add app="^Messages$" manage=off

# Scratch Pads
yabai -m rule --add app="^Music$" scratchpad=music grid=11:11:1:1:4:8
yabai -m rule --add app="^kitty$" scratchpad=kitty grid=11:11:1:1:4:8


yabai -m rule --add app="^Music$" title="^MiniPlayer$" manage=on
#yabai -m rule --add app="^Music$" manage=on
#yabai -m rule --add app="^Arc$" subrole="^AXSystemDialog$" manage=off mouse_follows_focus=off

borders active_color=0xff89b4fa width=7.0 blur_radius=0 &

# S K E T C H Y B A R  E V E N T S
yabai -m signal --add event=window_focused action="sketchybar -m --trigger window_focus &> /dev/null"
yabai -m signal --add event=window_title_changed action="sketchybar -m --trigger title_change &> /dev/null"
