#!/bin/bash

# Modes
:: default : borders active_color=0xff89b4fa ; sketchybar --trigger skhd_mode MODE=Default
:: active @ : borders active_color=0xffcdd6f4 ; sketchybar --trigger skhd_mode MODE=Active
:: scratchpad @ : borders active_color=0xffcba6f7 ; sketchybar --trigger skhd_mode MODE=Scratchpad
:: window @ : borders active_color=0xff89dceb ; sketchybar --trigger skhd_mode MODE=Window
:: restart @ : borders active_color=0xfff9e2af ; sketchybar --trigger skhd_mode MODE=Restart

# Mode shifting
default < alt - w ; window
default < alt - s ; scratchpad
default < alt - r ; restart

scratchpad, window, active, restart < escape ; default
scratchpad, window, active, restart < return ; default

# change window focus within space
window < s : yabai -m window --focus south
window < w : yabai -m window --focus north
window < a : yabai -m window --focus west
window < d : yabai -m window --focus east

# change focus between external displays (left and right)
window < q : yabai -m display --focus west
window < e : yabai -m display --focus east

# focus space window to space #
window < 1 : yabai -m space --focus 1;
window < 2 : yabai -m space --focus 2;
window < 3 : yabai -m space --focus 3;
window < 4 : yabai -m space --focus 4;
window < 5 : yabai -m space --focus 5;
window < 6 : yabai -m space --focus 6;
window < 7 : yabai -m space --focus 7;
window < 8 : yabai -m space --focus 8;
window < 9 : yabai -m space --focus 9;
window < 0 : yabai -m space --focus 10;

# move windows
window < down : yabai -m window --swap south
window < up : yabai -m window --swap north
window < left : yabai -m window --swap west
window < right : yabai -m window --swap east

# move window and split
window < shift - down : yabai -m window --warp south
window < shift - up : yabai -m window --warp north
window < shift - left : yabai -m window --warp west
window < shift - right : yabai -m window --warp east

# move window to display left and right
window < shift - q : yabai -m window --display west; yabai -m display --focus west
window < shift - e : yabai -m window --display east; yabai -m display --focus east

#move window to prev and next space
window < p : yabai -m window --space prev; yabai -m space --focus prev
window < n : yabai -m window --space next; yabai -m space --focus next

# move window to space #
window < shift - 1 : yabai -m window --space 1;
window < shift - 2 : yabai -m window --space 2;
window < shift - 3 : yabai -m window --space 3;
window < shift - 4 : yabai -m window --space 4;
window < shift - 5 : yabai -m window --space 5;
window < shift - 6 : yabai -m window --space 6;
window < shift - 7 : yabai -m window --space 7;
window < shift - 8 : yabai -m window --space 8;
window < shift - 9 : yabai -m window --space 9;
window < shift - 0 : yabai -m window --space 10;

#close window
window < backspace : osascript -e 'tell application "System Events" to perform action "AXPress" of (first button whose subrole is "AXCloseButton") of (first window whose subrole is "AXStandardWindow") of (first process whose frontmost is true)'

# toggle window float
ctrl + alt - f : yabai -m window --toggle float --grid 4:4:1:1:2:2; sketchybar --trigger window_focus

# maximize a window
ctrl + alt - m : yabai -m window --toggle zoom-fullscreen; sketchybar --trigger window_focus

#Scratchpads
scratchpad < t : yabai -m window --toggle kitty || open  -a kitty ; skhd -k 'escape'
scratchpad < m : yabai -m window --toggle music || open  -a Music ; skhd -k 'escape'
scratchpad < o : yabai -m window --toggle obsidian || open  -a Obsidian ; skhd -k 'escape'
scratchpad < d : yabai -m window --toggle discord || open  -a Discord ; skhd -k 'escape'

# Restart Service
restart < y : skhd -k 'escape' ; yabai --restart-service
restart < s : skhd -k 'escape' ; skhd --restart-service 
restart < k : skhd -k 'escape' ; brew services restart sketchybar
