[packages]
brew = [
    "font-hack-nerd-font",
    "jq",
    "starship",
    "font-sf-pro",
    "zsh-autosuggestions",
    "zsh-completions",
    "--cask sf-symbols",
    "ifstat",
    "--cask karabiner-elements",
    "eza",
    "fzf",
    "fd",
    "bat",
    "yabai",
    "skhd",
    "sketchybar",
    "trash",
    "thefuck",
    "tdlr",
    "--cask kitty",
    "borders",
    "--cask sol",
    "python@3.11",
    "git",
    "gh",
    "glow",
    "btop",
    "--cask font-ubuntu-nerd-font"
]
casks = [
    "homebrew/cask-fonts",
    "FelixKratz/formulae"
]