[packages]
brew = [
    "bat",
    "borders",
    "btop",
    "eza",
    "fd",
    "--cask font-sf-pro",
    "--cask font-ubuntu-sans-nerd-font",
    "fzf",
    "gh",
    "git",
    "glow",
    "ifstat",
    "jq",
    "--cask karabiner-elements",
    "kitty",
    "poetry",
    "python@3.11",
    "sketchybar",
    "skhd",
    "sf-symbols",
    "sol",
    "starship",
    "thefuck",
    "tdlr",
    "trash",
    "yabai",
    "zoxide",
    "zsh-autosuggestions",
    "zsh-completions"
]
casks = [
    "homebrew/cask-fonts",
    "FelixKratz/formulae"
]