#!/bin/bash

echo "Loading desktop config"

source "$CONFIG_DIR/colors.sh"


# -- Left Side Items --
source "$ITEM_DIR/apple.sh"
source "$ITEM_DIR/spaces.sh"
source "$ITEM_DIR/yabai.sh"
source "$ITEM_DIR/front_app.sh"

# -- Right Side Of Notch Items --
source "$ITEM_DIR/skhd.sh"
source "$ITEM_DIR/media.sh"

# --- Right Side Items ---
source "$ITEM_DIR/calendar.sh"
source "$ITEM_DIR/github.sh"
source "$ITEM_DIR/brew.sh"
source "$ITEM_DIR/volume.sh"
source "$ITEM_DIR/cpu.sh"
source "$ITEM_DIR/disk.sh"
source "$ITEM_DIR/ram.sh"
source "$ITEM_DIR/network.sh"
source "$ITEM_DIR/claude_usage.sh"
#source "$ITEM_DIR/wifi.sh"
#source "$ITEM_DIR/control_center.sh"


##### Finalizing Setup #####
# The below command is only needed at the end of the initial configuration to
# force all scripts to run the first time, it should never be run in an item script.
sketchybar --update
