#!/bin/bash

echo "Loading laptop config"

source "$CONFIG_DIR/colors.sh"

# -- Left Side Items --
source "$ITEM_DIR/apple.sh"
source "$ITEM_DIR/spaces.sh"
source "$ITEM_DIR/yabai.sh"
source "$ITEM_DIR/front_app.sh"

# -- Right Side Of Notch Items --
source "$ITEM_DIR/skhd.sh"
source "$ITEM_DIR/media.sh"

# --- Right Side Items ---
source "$ITEM_DIR/calendar.sh"
# source "$ITEM_DIR/wifi.sh"
source "$ITEM_DIR/battery.sh"
source "$ITEM_DIR/github.sh"
source "$ITEM_DIR/brew.sh"
source "$ITEM_DIR/volume.sh"
source "$ITEM_DIR/docker.sh"
source "$ITEM_DIR/cpu.sh"
source "$ITEM_DIR/disk.sh"
source "$ITEM_DIR/ram.sh"
source "$ITEM_DIR/network.sh"
source "$ITEM_DIR/claude_usage.sh"

##### Force all scripts to run the first time (never do this in a script) #####
sketchybar --update
