#!/bin/bash

source "$CONFIG_DIR/colors.sh"



# -- Left Side Items --
source "$ITEM_DIR/apple.sh"
source $ITEM_DIR/spaces.sh
source $ITEM_DIR/yabai.sh
source $ITEM_DIR/front_app.sh

# -- Right Side Of Notch Items --
source $ITEM_DIR/media.sh

# --- Right Side Items ---
source $ITEM_DIR/calendar.sh
source "$ITEM_DIR/github.sh"
source $ITEM_DIR/volume.sh
source $ITEM_DIR/battery.sh
source $ITEM_DIR/cpu.sh


##### Force all scripts to run the first time (never do this in a script) #####
sketchybar --update
