#!/bin/bash

SKETCHYBAR_CONFIG="$HOME/.config/sketchybar"

PLUGIN_DIR="$CONFIG_DIR/plugins"
ITEM_DIR="$CONFIG_DIR/items"

source "$CONFIG_DIR/colors.sh"
source "$CONFIG_DIR/icons.sh"

FONT="UbuntuSans Nerd Font" # Needs to have Regular, Bold, Semibold, Heavy and Black variants
FONT2="LED Dot-Matrix"
PADDINGS=2 # All paddings use this value (icon, label, background)
ITEM_BG_PADDING=2

# Unload the macOS on screen indicator overlay for volume change
launchctl unload -F /System/Library/LaunchAgents/com.apple.OSDUIHelper.plist > /dev/null 2>&1 &

# Setting up the general bar appearance of the bar
bar=(
  height=35
  color=$BAR_COLOR
  border_width=0
  border_color=$BAR_BORDER_COLOR
  blur_radius=20
  shadow=on
  position=top
  sticky=on
  padding_right=10
  padding_left=10
  y_offset=5
  margin=15
  topmost=window
  corner_radius=6
)
sketchybar --bar "${bar[@]}"

# Setting up default values
defaults=(
  updates=when_shown
  icon.font="$FONT:Bold:14.0"
  icon.align=center
  icon.color=$ICON_COLOR
  icon.padding_left=$PADDINGS
  icon.padding_right=$PADDINGS
  label.font="$FONT:Semibold:13.0"
  label.align=center
  label.color=$LABEL_COLOR
  label.padding_left=$PADDINGS
  label.padding_right=$PADDINGS
  padding_right=$ITEM_BG_PADDING
  padding_left=$ITEM_BG_PADDING
  background.height=24
  background.corner_radius=4
  background.border_width=0
  background.color=$BACKGROUND_1
  background.border_color=$HIGHLIGHT_COLOR
  popup.background.border_width=0
  popup.background.corner_radius=6
  popup.background.border_color=$POPUP_BORDER_COLOR
  popup.background.color=$POPUP_BACKGROUND_COLOR
  popup.blur_radius=20
  popup.background.shadow.drawing=on
  scroll_texts=off
)

sketchybar --default "${defaults[@]}"

# E V E N T S
sketchybar -m --add event window_focus \
              --add event title_change

# Toggle the bar
source "$ITEM_DIR/toggle.sh"

# This is used to determine if a monitor is used
# Since the notch is -only- on the laptop, if a monitor isn't used,
# then that means the internal display is used ¯\_(ツ)_/¯
MAIN_DISPLAY=$(system_profiler SPDisplaysDataType | grep -B 3 'Main Display:' | awk '/Display Type/ {print $3}')


if [[ $MAIN_DISPLAY = "Built-In" ]]; then
    source "$SKETCHYBAR_CONFIG/sketchybarrc-laptop"
else
    source "$SKETCHYBAR_CONFIG/sketchybarrc-desktop"
fi

